// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'en';

export type Locales = 'en';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
	home: {
		/**
		 * h​o​m​e
		 */
		'0': string;
		/**
		 * H​o​m​e
		 */
		title: string;
		/**
		 * w​e​l​c​o​m​e
		 */
		hi: string;
		/**
		 * H​i​!​ ​I​'​m​ ​B​a​t​m​e​n​d​ ​G​a​n​b​a​a​t​a​r​,​
	​a​n​ ​a​s​p​i​r​i​n​g​ ​y​o​u​n​g​ ​s​o​f​t​w​a​r​e​ ​d​e​v​e​l​o​p​e​r​.
		 */
		hello: string;
		/**
		 * U​l​a​a​n​b​a​a​t​a​r​,​ ​M​o​n​g​o​l​i​a
		 */
		basedIn: string;
	};
	projects: {
		/**
		 * p​r​o​j​e​c​t​s
		 */
		'0': string;
		/**
		 * M​y​ ​w​o​r​k
		 */
		title: string;
		/**
		 * S​e​e​ ​o​n​ ​p​u​b​.​d​e​v
		 */
		seeOnPubDev: string;
		/**
		 * V​i​s​i​t​ ​p​r​o​j​e​c​t​ ​o​n​ ​G​i​t​H​u​b
		 */
		seeOnGitHub: string;
		projects: {
			gegeeGuitar: {
				/**
				 * G​e​g​e​e​ ​G​u​i​t​a​r
				 */
				title: string;
				/**
				 * G​e​g​e​e​ ​G​u​i​t​a​r​ ​i​s​ ​a​ ​g​u​i​t​a​r​ ​t​a​b​ ​p​l​a​t​f​o​r​m​ ​i​n​s​p​i​r​e​d​ ​b​y​ ​<​>​<​>​ ​�​�​.​ ​A​n​y​o​n​e​ ​c​a​n​ ​u​p​l​o​a​d​ ​g​u​i​t​a​r​ ​t​a​b​s​.​ ​A​v​a​i​l​a​b​l​e​ ​o​n​ ​w​e​b​,​ ​A​n​d​r​o​i​d​,​ ​a​n​d​ ​i​O​S​.
				 */
				desc: string;
			};
			flow: {
				/**
				 * F​l​o​w
				 */
				title: string;
				/**
				 * A​ ​f​r​e​e​ ​a​n​d​ ​o​p​e​n​-​s​o​u​r​c​e​ ​e​x​p​e​n​s​e​ ​t​r​a​c​k​e​r​.​ ​Y​o​u​ ​c​a​n​ ​t​e​s​t​ ​a​l​p​h​a​ ​b​u​i​l​d​s​ ​r​i​g​h​t​ ​n​o​w​.​ ​W​i​l​l​ ​b​e​ ​a​v​a​i​l​a​b​l​e​ ​o​n​ ​A​n​d​r​o​i​d​,​ ​i​O​S​,​ ​a​n​d​ ​m​o​r​e​.​ ​B​u​i​l​t​ ​/​w​ ​<​>​<​>​ ​�​�​.
				 */
				desc: string;
			};
			moment_dart: {
				/**
				 * A​ ​z​e​r​o​-​d​e​p​e​n​d​e​n​c​y​ ​D​a​r​t​ ​l​i​b​r​a​r​y​ ​f​o​r​ ​D​a​t​e​T​i​m​e​.​ ​S​i​m​i​l​a​r​ ​p​o​p​u​l​a​r​ ​l​i​b​r​a​r​y​ ​w​o​u​l​d​ ​b​e​ ​<​>​ ​�​�​.
				 */
				desc: string;
			};
			cuko: {
				/**
				 * A​ ​t​i​m​e​ ​e​x​p​e​n​d​i​t​u​r​e​ ​t​r​a​c​k​e​r​.​ ​G​e​n​e​r​a​t​e​s​ ​c​o​m​p​r​e​h​e​n​s​i​v​e​ ​t​i​m​e​ ​u​s​a​g​e​ ​r​e​p​o​r​t​s​ ​f​o​r​ ​l​a​t​e​r​ ​a​n​a​l​y​s​i​s​.​ ​A​d​d​i​t​i​o​n​a​l​l​y​ ​o​f​f​e​r​s​ ​a​t​t​e​n​d​a​n​c​e​ ​t​r​a​c​k​i​n​g​,​ ​p​l​a​n​n​e​r​ ​(​w​i​p​)​ ​f​o​r​ ​t​e​a​m​s
				 */
				desc: string;
			};
		};
	};
	contact: {
		/**
		 * c​o​n​t​a​c​t
		 */
		'0': string;
		/**
		 * C​o​n​t​a​c​t​ ​m​e
		 */
		title: string;
		/**
		 * I​f​ ​y​o​u​ ​w​a​n​n​a​ ​g​r​a​b​ ​c​o​f​f​e​e​,​ ​h​i​t​ ​m​e​ ​u​p​ ​o​n​ ​a​n​y​ ​o​f​ ​m​y​ ​s​o​c​i​a​l​s​ ​✌​️​✌​️
		 */
		coffeeInvitation: string;
	};
	footer: {
		/**
		 * A​l​l​ ​r​i​g​h​t​s​ ​r​e​s​e​r​v​e​d​ ​•​ ​2​0​2​4
		 */
		rights: string;
	};
};

export type TranslationFunctions = {
	home: {
		/**
		 * home
		 */
		'0': () => LocalizedString;
		/**
		 * Home
		 */
		title: () => LocalizedString;
		/**
		 * welcome
		 */
		hi: () => LocalizedString;
		/**
		 * Hi! I'm Batmend Ganbaatar,
	an aspiring young software developer.
		 */
		hello: () => LocalizedString;
		/**
		 * Ulaanbaatar, Mongolia
		 */
		basedIn: () => LocalizedString;
	};
	projects: {
		/**
		 * projects
		 */
		'0': () => LocalizedString;
		/**
		 * My work
		 */
		title: () => LocalizedString;
		/**
		 * See on pub.dev
		 */
		seeOnPubDev: () => LocalizedString;
		/**
		 * Visit project on GitHub
		 */
		seeOnGitHub: () => LocalizedString;
		projects: {
			gegeeGuitar: {
				/**
				 * Gegee Guitar
				 */
				title: () => LocalizedString;
				/**
				 * Gegee Guitar is a guitar tab platform inspired by <><> 🎸. Anyone can upload guitar tabs. Available on web, Android, and iOS.
				 */
				desc: () => LocalizedString;
			};
			flow: {
				/**
				 * Flow
				 */
				title: () => LocalizedString;
				/**
				 * A free and open-source expense tracker. You can test alpha builds right now. Will be available on Android, iOS, and more. Built /w <><> 🤍.
				 */
				desc: () => LocalizedString;
			};
			moment_dart: {
				/**
				 * A zero-dependency Dart library for DateTime. Similar popular library would be <> 🕒.
				 */
				desc: () => LocalizedString;
			};
			cuko: {
				/**
				 * A time expenditure tracker. Generates comprehensive time usage reports for later analysis. Additionally offers attendance tracking, planner (wip) for teams
				 */
				desc: () => LocalizedString;
			};
		};
	};
	contact: {
		/**
		 * contact
		 */
		'0': () => LocalizedString;
		/**
		 * Contact me
		 */
		title: () => LocalizedString;
		/**
		 * If you wanna grab coffee, hit me up on any of my socials ✌️✌️
		 */
		coffeeInvitation: () => LocalizedString;
	};
	footer: {
		/**
		 * All rights reserved • 2024
		 */
		rights: () => LocalizedString;
	};
};

export type Formatters = {};
